---
apiVersion: v1
kind: Pod
metadata:
  name: nvidia-smi
  namespace: default
spec:
  hostPID: true
  restartPolicy: OnFailure
  runtimeClassName: nvidia
  nodeSelector:
    kubernetes.io/hostname: "fractalki"
  containers:
  - name: cuda-container
    image: nvidia/cuda:12.4.1-cudnn-runtime-ubuntu22.04
    securityContext:
      privileged: true
    # nvidia/cuda:12.2.2-runtime-ubuntu22.04
    #nvcr.io/nvidia/k8s/cuda-sample:nbody
    args: ["nvidia-smi", "-l"]
    env:
    - name: NVIDIA_VISIBLE_DEVICES
      value: all
    - name: NVIDIA_DRIVER_CAPABILITIES
      value: all
